#!/usr/bin/env bash
# A Bash script that displays a list of currently running processes
echo "PID   PPID   USER       COMMAND"
# Use ps command to get the list of processes
# -e shows all processes
# -f shows the full format, including PPID
# -H shows process hierarchy
processes=$(ps -e -f -H)
# Loop through the processes
while read -r line; do
  # Extract the PID, PPID, USER, and COMMAND fields
  pid=$(echo $line | awk '{print $2}')
  ppid=$(echo $line | awk '{print $3}')
  user=$(echo $line | awk '{print $1}')
  command=$(echo $line | awk '{print $8}')

  # Print the PID, PPID, USER, and COMMAND fields
  printf "%-5s %-5s %-10s %s\n" "$pid" "$ppid" "$user" "$command"
done <<< "$processes"
