#!/usr/bin/env bash
# classic fizzbuzz problem
A=(ph Fizz Buzz FizzBuzz)
for ((i=1;i<=100;i++)); do
	(( n=(i % 3 == 0) + (2 * (i % 5 == 0)) ))
	if (( n == 0 )); then
		echo "$i"
	else
		echo ${A[$n]}
	fi
done
