#!/usr/bin/env bash
# the good and bad luck
counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]; then
        echo "Bad luck"
    elif [ $counter -eq 8 ]; then
        echo "Good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
