#!/usr/bin/env bash
hours=0
minutes=0

while [ $hours -lt 12 ] || [ $minutes -lt 59 ]; do
  if [ $minutes -lt 59 ]; then
    minutes=$((minutes+1))
  else
    hours=$((hours+1))
    minutes=0
  fi
  printf "%02d:%02d\n" $hours $minutes
done
