#!/usr/bin/env bash
# checks if file exists and gives information about it
fn="./bootcampschool"
if [ -e "$fn" ]; then
	echo "bootcampschool file exists"
	if [ -s "$fn" ]; then
		echo "bootcampschool file is not empty"
	else
		echo "bootcampschool file is empty"
	fi
	if [ -f "$fn" ]; then
		echo "bootcampschool is a regular file"
	fi
else
	echo "bootcampschool file does not exist"
fi
